export const MODALS_ACTION_TYPES = {
  TOGGLE_NEW_PRODUCT_MODAL: 'OPEN_NEW_PRODUCT_MODAL',
  START_PRODUCT_EDIT: 'START_PRODUCT_EDIT',
  EDIT_PRODUCT_SUCCESS: 'EDIT_PRODUCT_SUCCESS',
  CANCEL_PRODUCT_EDIT: 'CANCEL_PRODUCT_EDIT'
};
