export const CART_ACTION_TYPES = {
  ADD_PRODUCT: 'ADD_PRODUCT',
  INCREMENT_PRODUCT: 'INCREMENT_PRODUCT',
  DECREMENT_PRODUCT: 'DECREMENT_PRODUCT',
  DELETE_PRODUCT_FROM_CART: 'DELETE_PRODUCT_FROM_CART',
  CHANGE_PRODUCT_COUNT: 'CHANGE_PRODUCT_COUNT',
  EMPTY_CART: 'EMPTY_CART',
};
