export const CART_ACTION_TYPES = {
  INCREMENT_PRODUCT: 'INCREMENT_PRODUCT',
  DECREMENT_PRODUCT: 'DECREMENT_PRODUCT',
  DELETE_FROM_CART: 'DELETE_FROM_CART',
  CHANGE_PRODUCT_COUNT: 'CHANGE_PRODUCT_COUNT'
};
