export const PRODUCT_ACTION_TYPES = {
  GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILURE: 'GET_PRODUCTS_FAILURE',
  DETAILS_LOADING: 'DETAILS_LOADING',
  DETAILS_FETCH_SUCCESS: 'DETAILS_FETCH_SUCCESS',
  DETAILS_FETCH_ERROR: 'DETAILS_FETCH_ERROR',
};
